### ISSUE TITLE
[Bug] GPU limit range selector setting does not work on Mac

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#765]
Steps to reproduce:

1. Go to: https://interactive-viewer-next.apps-dev.hbp.eu/
2. Go to settings
3. Decrease GPU limit to 100MB
4. Play on Big brain template - zoom in and out on the viewer
5. at the same time look at activity monitor GPU

expected behavior:
GPU Percentage should not exceed about 100MB by PC GPU storage

actual behavior:
On Mac with GPU storage of 4GB, it takes about 40% or more while loading

**Comment by xgui3783** [comment]
to diagnose the issue, while loading, can you provide:

```js
viewer.state.toJSON()['gpuMemoryLimit']
```

also please provide model of macbook, and screenshot of diagnosis please.

**Comment by fsdavid** [comment]
Thanks for the comment. 
First - I've used `viewer.state.toJSON()['gpuMemoryLimit']` and it is undefined after refresh.
Then - I'm set the GPU limit but the test looks same:
![image](https://user-images.githubusercontent.com/26521731/100591951-c433ba00-32f6-11eb-8e7e-a4cf876eda9d.png)
Macs Graphic memory is : 
![image](https://user-images.githubusercontent.com/26521731/100592086-ee857780-32f6-11eb-9776-3353e37c9f51.png)

**Comment by xgui3783** [comment]
issue should be fixed by #860 . once deploy completes, can you investigates again with the following steps:

1/ set gpu limit
2/ refresh page
3/ load any atlas, and look at gpu usage. 

BTW, default max gpu usage should be 1GB, so in the above example, viewer might not be only thing that's consuming vram

**Comment by fsdavid** [comment]
> issue should be fixed by #860 . once deploy completes, can you investigates again with the following steps:
> 
> 1/ set gpu limit
> 2/ refresh page
> 3/ load any atlas, and look at gpu usage.
> 
> BTW, default max gpu usage should be 1GB, so in the above example, viewer might not be only thing that's consuming vram

Yeah, I've tested and I'm still getting high GPU usege, but the 3D view loads much slower, so I think this is the case of how OS works itself. On the image, you can find that I was waiting a long time but Bigbrain's 3D view was not loaded yet. (So I think the issue is fixed now)
![image](https://user-images.githubusercontent.com/26521731/106827350-feb82b00-6688-11eb-9edf-13ace218ccda.png)
